import "server-only";
import { promises as fs } from "fs";
import path from "path";
import { NextResponse } from "next/server";
import { methodLabConfigured } from "@/lib/methodLab";

/**
 * One header and one footer for everything in the Method Lab.
 *
 * The gated documents are self-contained HTML files written at different times,
 * and each grew its own version of the confidential bar: three different wordings,
 * one document with no bar at all, another with no footer. Opening two of them in
 * a row looked like two different systems.
 *
 * So the chrome is no longer written into the documents. It is injected here, at
 * serve time, which means:
 *   - a document regenerated by a tool (the workbench, the data engine) picks up
 *     the current chrome without anyone remembering to paste it back in;
 *   - the wording, the links and the sign-out form exist in exactly one place;
 *   - a document opened on its own from disk is still a clean document.
 *
 * Any bar a file already carries is stripped before the shared one goes in, so
 * old files do not end up with two. The CSS is namespaced `ml-` and scoped to
 * the injected markup, so it cannot collide with a document's own styles.
 */

const NO_INDEX = "noindex, nofollow, noarchive, nosnippet";

/** The one wording. Changing it here changes it everywhere in the Lab. */
export const METHOD_LAB_NOTICE =
  "Confidential · Internal & invited viewers only · Not for distribution";

const SITE = "https://www.aperturemethod.com/";

const CHROME_CSS = `
.ml-bar{position:sticky;top:0;z-index:2147483000;display:flex;align-items:center;gap:14px;
  background:#500000;color:#fff;padding:7px 12px;font:700 11.5px/1.4 Arial,Helvetica,sans-serif;
  letter-spacing:.14em;text-transform:uppercase}
.ml-bar a,.ml-bar button{font:inherit;font-size:11px;color:#fff;background:transparent;
  border:1px solid rgba(255,255,255,.5);border-radius:3px;padding:4px 11px;text-decoration:none;
  white-space:nowrap;cursor:pointer;transition:background .15s,border-color .15s}
.ml-bar a:hover,.ml-bar button:hover{background:rgba(255,255,255,.14);border-color:#fff}
.ml-bar form{margin:0;flex:none}
.ml-bar .ml-note{flex:1;text-align:center;letter-spacing:.14em}
.ml-foot{border-top:1px solid #e2e0e0;margin-top:48px;padding:22px 28px 42px;
  font:400 12.5px/1.6 Arial,Helvetica,sans-serif;color:#6b6b6b;background:#fff;
  display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:12px}
.ml-foot .ml-f-links{display:flex;flex-wrap:wrap;gap:16px}
.ml-foot a{color:#500000;font-weight:700;text-decoration:none}
.ml-foot a:hover{text-decoration:underline}
.ml-foot button{font:inherit;color:#500000;font-weight:700;background:none;border:0;padding:0;
  cursor:pointer;text-decoration:none}
.ml-foot button:hover{text-decoration:underline}
.ml-foot form{margin:0}
@media print{.ml-bar,.ml-foot{display:none}}
@media (max-width:640px){
  .ml-bar{flex-wrap:wrap;justify-content:space-between;gap:8px;font-size:10px}
  .ml-bar .ml-note{order:3;flex-basis:100%;text-align:left;line-height:1.5}
}
`;

const BAR = `<div class="ml-bar">
  <a href="${SITE}">&#8592; Back to the site</a>
  <span class="ml-note">${METHOD_LAB_NOTICE.replace(/&/g, "&amp;")}</span>
  <a href="/method-lab">Method Lab home</a>
  <form method="POST" action="/api/method-lab/signout"><button type="submit">&#10005; Exit Method Lab</button></form>
</div>`;

const FOOT = `<div class="ml-foot">
  <span>The Aperture Method&trade; &middot; Method Lab &middot; ${METHOD_LAB_NOTICE.replace(
    /&/g,
    "&amp;"
  )}</span>
  <span class="ml-f-links">
    <a href="/method-lab">Method Lab home</a>
    <a href="${SITE}">Back to the site</a>
    <form method="POST" action="/api/method-lab/signout"><button type="submit">Exit Method Lab</button></form>
  </span>
</div>`;

/** Any bar a document still carries in its own markup. */
const OLD_BAR = /<div class="confbar"[\s\S]*?<\/div>\s*(?=<)/i;

/** Wraps a Method Lab document in the shared bar and footer. */
export function withMethodLabChrome(html: string): string {
  let out = html.replace(OLD_BAR, "");

  // After the opening <body …>, whatever attributes it carries.
  const body = /<body[^>]*>/i.exec(out);
  if (body) {
    const at = body.index + body[0].length;
    out = `${out.slice(0, at)}<style>${CHROME_CSS}</style>${BAR}${out.slice(at)}`;
  } else {
    out = `<style>${CHROME_CSS}</style>${BAR}${out}`;
  }

  const close = out.toLowerCase().lastIndexOf("</body>");
  out = close === -1 ? out + FOOT : out.slice(0, close) + FOOT + out.slice(close);

  return out;
}

/**
 * Serves one of the gated documents in `private/method-lab/`, with the shared
 * chrome around it. The files are kept out of `public/` on purpose: anything in
 * `public/` is served statically and cannot be gated by middleware.
 */
export async function serveMethodLabDocument(fileName: string): Promise<NextResponse> {
  if (!methodLabConfigured) {
    return new NextResponse("Not found", { status: 404 });
  }

  const file = path.join(process.cwd(), "private", "method-lab", fileName);

  try {
    const html = await fs.readFile(file, "utf8");
    return new NextResponse(withMethodLabChrome(html), {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "X-Robots-Tag": NO_INDEX,
        "Cache-Control": "private, no-store, max-age=0",
      },
    });
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }
}
